---
version: '3'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redis-data:/data
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    build: .
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=secret
    ports:
      - "8081:8081"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: admin 
    ports:
      - 8084:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  redis-data: